language: node_js
node_js:
  - 10.16.3

cache: yarn

env:
  - NODE_ENV=test

before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FA_TOKEN

install:
  - yarn global add jest
script:
  - yarn 
  - yarn lint
  - yarn test

# Add Heroku deploy using 'travis set heroku'